basePath: /api
definitions:
  v1.Chunking:
    properties:
      overlap:
        description: Overlap between chunks.
        type: integer
      sep:
        description: Sep keeps separator in chunks.
        type: boolean
      size:
        description: Size of each chunk.
        type: integer
      trim:
        description: Trim empty space chars.
        type: boolean
    type: object
  v1.ChunkingInput:
    properties:
      input:
        description: Input to split into chunks.
        type: string
      options:
        allOf:
        - $ref: '#/definitions/v1.Chunking'
        description: Options to configure chunking.
    type: object
  v1.ChunkingResponse:
    properties:
      chunks:
        description: Chunks contain indices into the chunked input.
        items:
          items:
            type: integer
          type: array
        type: array
    type: object
  v1.Embedding:
    properties:
      metadata:
        additionalProperties: {}
        description: Metadata for the given embedding vector.
        type: object
      uid:
        description: UID is the unique ID for this embedding.
        type: string
      value:
        description: |-
          Values stores embedding vector values.
          NOTE: the key is set to value - singular
          because the API is consumed by ECharts and
          it's just sad ECharts expects value slice.
          We could handle that in JS but who can be bothered?
        items:
          type: number
        type: array
    type: object
  v1.EmbeddingsResponse:
    properties:
      embeddings:
        items:
          $ref: '#/definitions/v1.Embedding'
        type: array
      page:
        $ref: '#/definitions/v1.Page'
    type: object
  v1.EmbeddingsUpdate:
    properties:
      chunking:
        $ref: '#/definitions/v1.Chunking'
      label:
        type: string
      metadata:
        additionalProperties: {}
        type: object
      projection:
        $ref: '#/definitions/v1.Projection'
      text:
        type: string
    type: object
  v1.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  v1.Page:
    properties:
      count:
        description: |-
          Count is the number of all
          results if provided.
        type: integer
      next:
        description: |-
          Next is either a number
          or a string ID which allows
          resuming paging if provided.
        type: string
    type: object
  v1.Projection:
    enum:
    - tsne
    - pca
    type: string
    x-enum-varnames:
    - TSNE
    - PCA
  v1.ProjectionsResponse:
    properties:
      embeddings:
        additionalProperties:
          items:
            $ref: '#/definitions/v1.Embedding'
          type: array
        type: object
      page:
        $ref: '#/definitions/v1.Page'
    type: object
  v1.ProjectionsUpdate:
    properties:
      metadata:
        additionalProperties: {}
        type: object
      projection:
        $ref: '#/definitions/v1.Projection'
    type: object
  v1.Provider:
    properties:
      id:
        description: UID of the provider's UUID.
        type: string
      metadata:
        additionalProperties: {}
        description: Metadata about the provider.
        type: object
      name:
        description: Name is the name of the provider
        type: string
    type: object
  v1.ProvidersResponse:
    properties:
      page:
        $ref: '#/definitions/v1.Page'
      providers:
        items:
          $ref: '#/definitions/v1.Provider'
        type: array
    type: object
info:
  contact: {}
  description: This is an API for fetching embeddings.
  termsOfService: http://swagger.io/terms/
  title: Embeddings API
  version: "1.0"
paths:
  /v1/chunks:
    post:
      consumes:
      - application/json
      description: Get chunks from the given input
      parameters:
      - description: Get input chunks
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/v1.ChunkingInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/v1.ChunkingResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: Get chunks from the given input.
      tags:
      - providers
  /v1/providers:
    get:
      description: Get all available providers.
      parameters:
      - description: Result offset
        in: query
        name: offset
        type: integer
      - description: Result limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.ProvidersResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: Get all embeddings providers.
      tags:
      - providers
  /v1/providers/{uid}:
    get:
      description: Returns embeddings provider with the given UID.
      parameters:
      - description: Provider UID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Provider'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: Get embeddings provider by UID.
      tags:
      - providers
  /v1/providers/{uid}/embeddings:
    delete:
      description: Delete embeddings by provider UID. This also drops projections.
      parameters:
      - description: Provider UID
        in: path
        name: uid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Provider embeddings deleted successfully
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: Delete embeddings by provider UID.
      tags:
      - providers
    get:
      description: Returns embeddings for the provider with the given UID.
      parameters:
      - description: Provider UID
        in: path
        name: id
        required: true
        type: string
      - description: Result offset
        in: query
        name: offset
        type: integer
      - description: Result limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.EmbeddingsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: Get embeddings by provider UID.
      tags:
      - providers
    put:
      consumes:
      - application/json
      description: Update provider embeddings.
      parameters:
      - description: Provider UID
        in: path
        name: id
        required: true
        type: string
      - description: Update provider embeddings
        in: body
        name: provider
        required: true
        schema:
          $ref: '#/definitions/v1.EmbeddingsUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/v1.Embedding'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: Fetch and store embeddings for the provider with the given UID.
      tags:
      - providers
  /v1/providers/{uid}/projections:
    get:
      description: Returns embedding projections for the provider with the given UID.
      parameters:
      - description: Provider UID
        in: path
        name: id
        required: true
        type: string
      - description: Result offset
        in: query
        name: offset
        type: integer
      - description: Result limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.ProjectionsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: Get embeddings projections by provider UID.
      tags:
      - providers
    patch:
      consumes:
      - application/json
      description: Recompute provider projections.
      parameters:
      - description: Provider UID
        in: path
        name: id
        required: true
        type: string
      - description: Update embeddings projections
        in: body
        name: provider
        required: true
        schema:
          $ref: '#/definitions/v1.ProjectionsUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Embedding'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.ErrorResponse'
      summary: Recompute embeddings projections for a provider by UID and return them.
      tags:
      - providers
swagger: "2.0"
